Tech stack: {
  Client: "Client (Client Side Rendering)"
  Client: {
    Bun
    Vite
    Preact
    Playwright
    Typedoc
    D2lang
    Mantine
    Lucide
  }
  Client -> Server
  Server: {
    Bun
    Bun test
    Typedoc
    D2lang
    Elysia
    Elysia/swagger
  }
}
